---
title: "BCB520 Test Codes"
format:
  pdf:
    warning: FALSE
    keep-tex: true
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
include-before-body:
  text: |
    \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaksymbolleft={},
      breaklines
      % Note: setting commandchars=\\\{\} here will cause an error 
    }
editor: source
---

## Data Preparation

```{r, 'load packages'}
suppressMessages({
  library(here)
  library(readxl)
  library(dplyr)
  library(tidyr)
  library(brms)
  library(car)
  library(ggplot2)})
```

```{r, 'data'}
data <- read_excel(here::here("data", "viz_data.xlsx"), na="NA") |> 
  mutate(day = factor(day, levels = sort(as.numeric(unique(day))), ordered = TRUE), 
         location = as.factor(location), 
         primal = as.factor(primal), 
         trt = as.factor(trt), 
         eval = factor(eval, levels = unique(eval)),
         flean = as.factor(lean),
         fbrown = as.factor(brown),
         fdisc = as.factor(disc),
         fsurface = as.factor(surface),
         funi = as.factor(uni)) |>
  mutate(sample = paste(primal, location, trt, sep = "_")) |>
  na.exclude()  
```

```{r, results='hide', echo=FALSE}
#Checking data/missing values with tables
any(is.na(data))
table(data$day)

table(data$lean)
table(data$brown)
table(data$disc)
table(data$surface)
table(data$uni)

table(data$flean)
table(data$fbrown)
table(data$fdisc)
table(data$fsurface)
table(data$funi)
```
## Eval differences
```{r, 'viz'}
ggplot2::ggplot(data, aes(x = day, y = lean, fill = eval)) + 
  geom_boxplot() +
  labs(x = "Retail Day", y = "Lean Color", fill = "Evaluator") +
  scale_y_continuous(limits = c(1,8), breaks = seq(1,8, by = 0.5)) +
  theme_bw()
```